// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJCaUGp2OetW7o5fsalxAro2bIYfcgMZg',
    appId: '1:918957779709:web:58f15178c1f94b8ef52c94',
    messagingSenderId: '918957779709',
    projectId: 'buildmypc-9ddd0',
    authDomain: 'buildmypc-9ddd0.firebaseapp.com',
    storageBucket: 'buildmypc-9ddd0.firebasestorage.app',
    measurementId: 'G-2Y9GSJ8STT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4GI3UV6Ga61APk02wAB1dP6b1IIqkGnA',
    appId: '1:918957779709:android:37eb02d3706dd895f52c94',
    messagingSenderId: '918957779709',
    projectId: 'buildmypc-9ddd0',
    storageBucket: 'buildmypc-9ddd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8mhOeZEUEMEs4MTgpdVBq_kn68oV68gE',
    appId: '1:918957779709:ios:1510048d6fca1a22f52c94',
    messagingSenderId: '918957779709',
    projectId: 'buildmypc-9ddd0',
    storageBucket: 'buildmypc-9ddd0.firebasestorage.app',
    iosBundleId: 'com.example.softwareEngineeringProjectPcKonfigurationApp',
  );
}
